### ISSUE TITLE
spherenet xyz_to_dat repeat_interleave issue

### ISSUE THREAD

**Issue by josejimenezluna** [keiradams/ChIRo#2]
Hi, first of all many thanks for open-sourcing this!

I was checking out your implementation of the SphereNet architecture, and I noticed that I cannot successfully perform a forward pass of the network. Namely, the problem appears to lie in the `xyz_to_dat` function defined within that submodule. 

I start with 3D coordinates in cartesian space and compute edge indices according `torch_geometric.nn.pool.radius_graph`:

```python
In [13]: g.coords
Out[13]: 
tensor([[ 4.5877,  1.2124,  0.9045],
        [ 3.4939,  2.0393,  0.7065],
        [ 2.5577,  1.7294, -0.2622],
        [ 2.6985,  0.5842, -1.0372],
        [ 1.6548,  0.2541, -2.0763],
        [ 0.3290,  0.2897, -1.5940],
 ...]])

In [14]: g.coords.shape
Out[14]: torch.Size([41, 3])


In [16]: edge_index = radius_graph(g.coords, r=5.0, batch=torch.zeros(g.atomids.size(0), dtype=int))

In [17]: edge_index
Out[17]: 
tensor([[20,  1, 19,  ...,  2,  4,  3],
        [ 0,  0,  0,  ..., 40, 40, 40]])

In [18]: edge_index.shape
Out[18]: torch.Size([2, 937])

```

I then try and call the `xyz_to_dat` routine present in the forward pass, and I encounter this error:

```
In [20]:     out = xyz_to_dat(pos=g.coords, edge_index=edge_index, num_nodes=g.atomids.size(0), use_torsion=True)
    ...: 
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-e5d12c7af566> in <module>
----> 1 out = xyz_to_dat(pos=g.coords, edge_index=edge_index, num_nodes=g.atomids.size(0), use_torsion=True)

~net.py in xyz_to_dat(pos, edge_index, num_nodes, use_torsion)
    114     repeat = num_triplets - 1
    115     num_triplets_t = num_triplets.repeat_interleave(repeat)
--> 116     idx_i_t = idx_i.repeat_interleave(num_triplets_t)
    117     idx_j_t = idx_j.repeat_interleave(num_triplets_t)
    118     idx_k_t = idx_k.repeat_interleave(num_triplets_t)

RuntimeError: repeats must have the same size as input along dim

```

I'm wondering whether the problem is on my side and I'm misunderstanding how these functions shoud be called. Any help is appreciated!

**Comment by keiradams** [comment]
I've had the same issue when using this implementation of SphereNet (from https://github.com/divelab/DIG), see the Appendix A.5.2 of our preprint https://arxiv.org/abs/2110.04383. I found that this error can occur for some conformers of the same molecule, but not others. I wish I could be of more help!

**Comment by josejimenezluna** [comment]
Dear @keiradams,

Many thanks for your swift reply - in my case this routine fails way more often, with a higher tendency for failure in larger molecules:

![image](https://user-images.githubusercontent.com/6875576/138301342-f521492c-7402-45d6-b928-6af148043933.png)

I guess I'll try my luck opening an issue in the repo link you mentioned.
Thanks again!
