### ISSUE TITLE
question about `get_local_structure_map`

### ISSUE THREAD

**Issue by linminhtoo** [keiradams/ChIRo#3]
hello Keir,

Nice work on ChIRo! we've been exploring its application for the task of protein-ligand affinity prediction at my startup.

I have gotten the model to train and it seems to be working, but I have a question about the way `get_local_structure_map` is defined. I noticed that it's meant to work on batches of `psi_indices`. Is there any specific reason why this was done? Would it be possible to define a similar function that just generates the input features `LS_map` and `alpha_indices` for one molecule at a time? This is more from an engineering perspective. 

https://github.com/keiradams/ChIRo/blob/2686d3a1801db8fb3dec10b61fb0cb0cec047c7c/model/train_functions.py#L22-L37

Thanks!

**Comment by keiradams** [comment]
Hi Min Htoo, sorry for the delayed response! I'm glad you've gotten use out of ChIRo. As per your question, there's no reason why I initially made `get_local_structure_map` operate on batches of `psi_indices` apart from convenience. Note that it was designed to be used with `torch_geometric` dataloaders, which automatically increment `psi_indices` by the total number of nodes/atoms in each graph/molecule. If applied to one molecule at a time separately, you'd want to ensure that `alpha_indices` and `LS_map` are incremented properly (that is, if you plan to batch those individual molecules together).

**Comment by linminhtoo** [comment]
Got it, thanks!
